name: Continuous integration
on: [push]
env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 0

jobs:
  test-nixpkgs:
    name: Build & Test - Nixpkgs
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Mount Bazel cache
        uses: actions/cache@v2
        with:
          path: ~/repo-cache
          key: repo-cache-${{ runner.os }}-nixpkgs-${{ env.cache-version }}
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=./nixpkgs.nix
      - name: Configure
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        run: |
          cat >.bazelrc.local <<EOF
          build --host_platform=@io_tweag_rules_nixpkgs//nixpkgs/platforms:host
          build --bes_results_url=https://app.buildbuddy.io/invocation/
          build --bes_backend=grpcs://cloud.buildbuddy.io
          build --remote_cache=grpcs://cloud.buildbuddy.io
          build --remote_header=x-buildbuddy-api-key="$BUILDBUDDY_API_KEY"
          build --repository_cache=~/repo-cache/
          EOF
          ln -s ../.bazelrc.local example/.bazelrc.local
      - name: Build & run gazelle
        run: cd example; nix-shell --pure --run 'bazel run //:gazelle'
      - name: Build & test generated rules
        run: cd example; nix-shell --pure --run 'bazel test //...'
      - name: Test for buildifier suggestions
        run: nix-shell --pure --run 'bazel run //:buildifier-diff'
